language: swift
xcode_project: TravisCIDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: TravisCIDemo
xcode_destination: platform=iOS Simulator, id=C0BD112C-A78A-491A-A827-DB464992E80E, OS=11.4, name=iPhone X

env:
  # global:
  #   - LANG=en_US.UTF-8
  #   - LC_ALL=en_US.UTF-8
  #   - XCODE_PROJECT=core/TravisCIDemo.xcodeproj
  matrix:
    - SCHEME="TravisCIDemo"

before_install:
  - pod install
